blog/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField,SubmitField,PasswordField,SelectField,BooleanField
from wtforms import TextAreaField
from wtforms.validators import Length,DataRequired,Required
from app.models import Role
from flask_pagedown.fields import PageDownField

class EditUserinfo(FlaskForm):
    location = StringField(label='所在地',validators=[Length(0,64)])
    about_me = TextAreaField(label='AboutMe')
    submit = SubmitField(label='提交')

class EditAdminForm(FlaskForm):
    name = StringField(label='姓名')
    password = PasswordField(label='密码')
    role_id = SelectField(label='角色',coerce=int)
    comfirmed = BooleanField(label='邮箱认证')
    location = StringField(label='所在地')
    about_me = TextAreaField(label='AboutMe')
    submit = SubmitField(label='提交')

    def __init__(self,*args,**kwargs):
        super(EditAdminForm, self).__init__(*args,**kwargs)
        self.role_id.choices = [(role.id,role.name) for role in (Role.query.order_by(Role.id).all())]


class BlogForm(FlaskForm):
    title = StringField(label='博客标题',validators=[DataRequired()])
    body = PageDownField(label='博客正文',validators=[DataRequired()])
    submit = SubmitField(label='提交')


class CommentForm(FlaskForm):
    comment = TextAreaField(validators=[DataRequired()])
    submit = SubmitField(label='评论')

blog/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

blog/app/main/views.py
from flask import render_template, session, abort, redirect, url_for, request
from . import main
from app.models import User, db, Blog, Follow, Comment
from .forms import EditUserinfo, EditAdminForm, BlogForm, CommentForm
from flask_login import login_required, current_user
from app.decorators import admin_decorator, permission_decorator
from app.decorators import Permission


@main.route('/', methods=['GET', 'POST'])
def index():
    # blogs = Blog.query.order_by(Blog.time.desc()).all()
    page = request.args.get('page', 1, type=int)
    pagination = Blog.query.order_by(Blog.time.desc()).paginate(page, 5, False)
    blogs = pagination.items
    return render_template('main/index.html', pagination=pagination, blogs=blogs)


@main.route('/write_blog', methods=['GET', 'POST'])
@login_required
@permission_decorator(Permission.WRITE)
def write_blog():
    form = BlogForm()
    if form.validate_on_submit():
        blog = Blog()
        blog.title = form.title.data
        blog.body = form.body.data.replace("\n", "<br>")
        blog.author_id = current_user.id
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('main/write_blog.html', form=form)


@main.route('/user/<path:name>')
@login_required
def user_info(name):
    user = User.query.filter_by(name=name).first()
    if user is None:
        abort(404)
    # blogs = Blog.query.filter_by(author=user).order_by(Blog.time.desc()).all()
    page = request.args.get('page', 1, type=int)
    pagination = user.blogs.order_by(Blog.time.desc()).paginate(page, 5, False)
    blogs = pagination.items
    return render_template('main/user_info.html', user=user, blogs=blogs, pagination=pagination)


@main.route('/edit_user_info', methods=['GET', 'POST'])
@login_required
def edit_user_info():
    form = EditUserinfo()
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.user_info', name=current_user.name))
    return render_template('main/edit_user_info.html', form=form)


@main.route('/edit_admin', methods=['GET', 'POST'])
@login_required
@admin_decorator
def edit_admin():
    id = request.args.get('id', None)
    if id is None:
        abort(404)
    user = User.query.filter_by(id=id).first()
    form = EditAdminForm()
    if form.validate_on_submit():
        u1 = User.query.filter_by(name=form.name.data).first()
        if u1 is None:
            abort(404)
        if u1 and u1 != user:
            return redirect(url_for('main.user_info', name=user.name))
        user.name = form.name.data
        if form.password.data:
            user.password = form.password.data
        user.about_me = form.about_me.data
        user.location = form.location.data
        user.role_id = form.role_id.data
        user.confirmed = form.comfirmed.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.user_info', name=user.name))
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    form.comfirmed.data = user.confirmed
    form.role_id.data = user.role_id
    return render_template('main/edit_admin.html', form=form)


@main.route('/blog/<id>', methods=['GET', 'POST'])
@login_required
def blog(id):
    if id is None:
        abort(404)
    blog = Blog.query.filter_by(id=int(id)).first()
    if blog is None:
        abort(404)
    form = CommentForm()
    if current_user.has_permission(Permission.COMMENT):
        if form.validate_on_submit():
            comment = Comment()
            comment.blog_id = blog.id
            comment.author_id = current_user.id
            comment.body = form.comment.data
            comment.disabled = False
            db.session.add(comment)
            db.session.commit()
            return redirect(url_for('main.blog', id=blog.id))
    # comments = Comment.query.filter_by(blog_id = blog.id).all()
    page = request.args.get('page', type=int, default=1)
    pagination = blog.comments.order_by(Comment.time.desc()).paginate(page, 3, False)
    comments = pagination.items
    return render_template('main/blog.html', blog=blog, form=form, comments=comments, pagination=pagination)


@main.route('/blog_delete')
@login_required
def blog_delete():
    blog_id = request.args.get('blog_id')
    if blog_id is None:
        abort(404)
    blog = current_user.blogs.filter_by(id=blog_id).first()
    if blog is None:
        abort(404)
    db.session.delete(blog)
    db.session.commit()
    return redirect(url_for('main.user_info', name=current_user.name))


@main.route('/follow')
@permission_decorator(Permission.FOLLOW)
def follow():
    uid = request.args.get('uid')
    if uid is None:
        abort(404)
    user = User.query.filter_by(id=uid).first()
    if user is None:
        abort(404)
    current_user.follow(user)
    return redirect(url_for('main.user_info', name=user.name))


@main.route('/unfollow')
@permission_decorator(Permission.FOLLOW)
def unfollow():
    uid = request.args.get('uid')
    if uid is None:
        abort(404)
    user = User.query.filter_by(id=uid).first()
    if user is None:
        abort(404)
    current_user.unfollow(user)
    return redirect(url_for('main.user_info', name=user.name))


@main.route('/fans')
@login_required
def fans():
    uid = request.args.get('uid')
    if uid is None:
        abort(404)
    user = User.query.filter_by(id=uid).first()
    fans = user.followers.order_by(Follow.time.desc()).all()
    fans_list = []
    for fan in fans:
        fans_list.append(fan.follower)
    return render_template('main/fans.html', fans_list=fans_list)

blog/app/templates/main/blog.html
{% extends 'base.html' %}
{% block page_content %}
    <div class="page-header">
        <font size="8" color="orange">{{ blog.title }}</font><br>
        <font size="5" color="red"><a
                href="{{ url_for('main.user_info',name=blog.author.name) }}"
                class="btn-link btn">{{ blog.author.name }}</a></font><br>
        <font color="aqua">{{ blog.time }}{{ moment(blog.time).fromNow() }}</font><br>
        {% if blog.body_html %}
            {{ blog.body_html|safe }}
        {% else %}
            {{ blog.body | safe }}<br>
        {% endif %}
    </div>
{% endblock %}
{% block page_content2 %}
    {% import '_macro.html'as macro %}
    {{ macro.pagination_widget(pagination,'main.blog',id=blog.id) }}
{% endblock %}
{% block page_content1 %}
    {% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
    {% for comment in comments %}
    {{ comment.body|safe }}<br>
    <a href="{{ url_for('main.user_info',name=comment.comment_man) }}">{{ comment.comment_man.name }}</a>
    {{ moment(comment.time).fromNow() }}<hr>
    {% endfor %}
{% endblock %}

blog/app/templates/main/edit_admin.html
{% extends 'base.html' %}
{% block page_content %}
    {% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}

blog/app/templates/main/edit_user_info.html
{% extends 'base.html' %}
{% block page_content %}
    {% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}

blog/app/templates/main/fans.html
{% extends 'base.html' %}
{% block page_content %}
    {% for fan in fans_list %}
        <a href="{{ url_for('main.user_info',name=fan.name) }}" class="btn panel-info">{{ fan.name }}</a>
    {% endfor %}
{% endblock %}

blog/app/templates/main/index.html
{% extends 'base.html' %}
{% block page_content1 %}
   <h2>欢迎,{{ current_user.name }}!!</h2>
{% endblock %}
{% block page_content2 %}
    {% include 'blogs.html' %}
    {% import '_macro.html' as macro %}
    {{ macro.pagination_widget(pagination,'main.index') }}
{% endblock %}

blog/app/templates/main/user_info.html
{% extends 'base.html' %}
{% block page_content %}

    <span class="label label-info">姓名</span>{{ user.name }}<br>
    <span class="label label-info">邮箱</span>{{ user.email }}<br>
    {% if user.location %}
        <span class="label label-info">位置</span><a href="https://www.baidu.com/s?wd={{ user.location }}">{{ user.location }}</a><br>
    {% else %}
        <span class="label label-info">位置</span>没有设定位置<br>
    {% endif %}
    <span class="label label-info">描述</span>{{ user.about_me }}<br>
    {% if user.role %}
        <span class="label label-info">角色</span>{{ user.role.name }}<br>
        {% if current_user.is_admin() %}
            <span class="label label-info">邮箱</span><a href="mailto:{{ user.email }}">{{ user.email }}</a>
        {% else %}
            <span class="label label-info">邮箱</span>{{ user.email }}
        {% endif %}
    {% endif %}<br>
    {% if user.confirmed %}
        <span class="label label-info">邮箱验证</span>是
    {% else %}
        <span class="label label-info">邮箱验证</span>否
    {% endif %}<br>

    <span class="label label-info">注册时间</span>{{ moment(user.register_time).format('LLLL') }}<br>

    <span class="label label-info">最后访问时间</span>{{ moment(user.access_time).fromNow() }}<br>


    {% if current_user == user and not current_user.is_admin() %}
        <a class="btn btn-danger" href="{{ url_for('main.edit_user_info') }}">编辑资料</a>
    {% elif current_user.is_admin() %}
        <a class="btn btn-danger" href="{{ url_for('main.edit_admin',id = user.id) }}">编辑资料</a>
    {% endif %}
    {% if current_user == user %}
        <a class="btn btn-info" href="{{ url_for('main.write_blog') }}">发表博客</a>
    {% endif %}
    {% if current_user.is_follower_of(user) %}
        <a href="{{ url_for('main.unfollow',uid=user.id) }}" class="btn bg-success">取消关注</a>
    {% else %}
        <a href="{{ url_for('main.follow',uid=user.id) }}" class="btn bg-success">关注</a>
    {% endif %}
    <a href="{{ url_for('main.fans',uid=user.id) }}" class="btn btn-info">粉丝{{ user.followers.count() }}</a>
{% endblock %}
{% block page_content2 %}
    {% include 'blogs.html' %}
 {% import '_macro.html'as macro %}
    {{ macro.pagination_widget(pagination,'main.user_info',name=user.name) }}
{% endblock %}

blog/app/templates/main/write_blog.html
{% extends 'base.html' %}
{% block page_content %}
 {% import 'bootstrap/wtf.html'as wtf %}
    {% if current_user.has_permission(Permission.WRITE) %}
        {{ wtf.quick_form(form) }}
    {% endif %}
{% endblock %}