iot/app/manager/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField,SelectField,StringField,PasswordField,BooleanField
from wtforms.validators import DataRequired,Length,Email,EqualTo,ValidationError
from app.models import Role,User

class UserForm(FlaskForm):
    email = StringField(label='邮箱', validators=[DataRequired(), Length(1, 64), Email()])
    name = StringField(label='姓名', validators=[DataRequired(), Length(1, 32)])
    password = PasswordField(label='密码', validators=[DataRequired(), Length(1, 64)])
    password_again = PasswordField(label='确认密码',validators=[DataRequired(), Length(1, 64), EqualTo('password', message='密码不正确')])
    location = StringField(label='位置')
    about_me = StringField(label='描述')
    confirmed = BooleanField(label='邮箱认证')
    role_id = SelectField(label='角色',coerce=int)
    submit = SubmitField(label='添加用户')

    def __init__(self):
        super(UserForm,self).__init__()
        self.role_id.choices = [(role.id, role.name) for role in (Role.query.order_by(Role.id).all())]
    def validate_name(self,field):
        user = User.query.filter_by(name=field.data).first()
        if user is not None:
            raise ValidationError('用户名存在')
    def validate_email(self,field):
        user = User.query.filter_by(email=field.data).first()
        if user is not None:
            raise ValidationError('邮箱已经存在')


iot/app/manager/__init__.py
from flask import Blueprint

manager = Blueprint('manager', __name__)
from . import forms, views

iot/app/manager/views.py
from . import manager
from flask import render_template, url_for, redirect, request, abort
from app.decorators import permission_decorator, admin_decorator, assient_decorator
from app.models import Permission, User
from app import db
from flask_login import login_required
from .forms import UserForm


@manager.route('/manager_user')
@login_required
@admin_decorator
def manager_user():
    page = request.args.get('page', 1, type=int)
    pagination = User.query.order_by(User.register_time.desc()).paginate(page, 10, False)
    users = pagination.items
    return render_template('manager/manager_user.html', users=users, pagination=pagination)


@manager.route('/manager_delete_user')
@login_required
@admin_decorator
def manager_delete_user():
    id = request.args.get('id')
    if id is None:
        abort(404)
    user = User.query.filter_by(id = id ).first()
    if user is None:
        abort(404)
    db.session.delete(user)
    db.session.commit()
    page = request.args.get('page',1,type=int)
    pagination = User.query.order_by(User.register_time.desc()).paginate(page,10,False)
    users = pagination.items
    return redirect(url_for('.manager_user',pagination=pagination,users=users))




@manager.route('/decorator')
@assient_decorator
def manager_decorator():
    return render_template('manager/manager_user.html')


@manager.route('/manager_add_user',methods=['GET','POST'])
@admin_decorator
def manager_add_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User()
        user.email = form.email.data
        user.name = form.name.data
        user.password = form.password.data
        user.role_id = form.role_id.data
        user.about_me = form.about_me.data
        user.location = form.location.data
        user.confirmed = form.confirmed.data
        print(form.confirmed.data)
        db.session.add(user)
        db.session.commit()
        user.generate_api()
        return redirect(url_for('.manager_user'))
    return render_template('manager/manager_add_user.html',form=form)




iot/app/templates/manager/edit_user.html
{% extends 'base.html' %}
{% block page_content %}
    {% import 'bootstrap/wtf.html' as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}

iot/app/templates/manager/manager_add_user.html
{% extends 'base.html' %}
{% block bodystyle %}
    <body class="index">
{% endblock %}
{% block page_content %}
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        {% if current_user.is_admin() %}
            <a href="{{ url_for('manager.manager_user') }}" class="btn btn-info">
                用户管理
            </a>
            <a href="{{ url_for('manager.manager_add_user') }}" class="active btn btn-info">
                新增用户
            </a>
        {% endif %}
    </div>
{% endblock %}
{% block page_content1 %}
    {% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}
</body>

iot/app/templates/manager/manager_user.html
{% extends 'base.html' %}
{% block bodystyle %}
    <body class="index">
{% endblock %}
{% block page_content %}
    <div class="btn-group btn-group-justified" role="group" aria-label="...">
        {% if current_user.is_admin() %}
            <a href="{{ url_for('manager.manager_user') }}" class="active btn btn-info">
                用户管理
            </a>
            <a href="{{ url_for('manager.manager_add_user') }}" class="btn btn-info">
                新增用户
            </a>
        {% endif %}
    </div>
{% endblock %}
{% block page_content1 %}
    <div class="panel panel-info">
        <!-- Default panel contents -->
        <div class="panel-heading" align="center">用户信息</div>
        <!-- Table -->
        <table class="table" border="1">
            <tr>
                <th>邮箱</th>
                <th>用户名</th>
                <th>位置</th>
                <th>详情</th>
                <th>删除</th>
            </tr>
            {% for user in users %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>{{ user.name }}</td>
                    <td>{{ user.location }}</td>
                    <td><a href="{{ url_for('main.user_info',name=user.name) }}">详情</a></td>
                    <td><a href="{{ url_for('manager.manager_delete_user',id = user.id,page=pagination.page) }}">删除</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    {% import '_macro.html' as macro %}
    <div align="center">{{ macro.pagination_widget(pagination,'manager.manager_user') }}</div>
{% endblock %}
</body>