iot/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField,SubmitField,PasswordField,SelectField,BooleanField,FloatField
from wtforms import TextAreaField
from wtforms.validators import Length,DataRequired
from app.models import Role,Stype


class EditUserinfo(FlaskForm):
    location = StringField(label='所在地',validators=[Length(0,64)])
    about_me = TextAreaField(label='AboutMe')
    submit = SubmitField(label='提交')

class EditAdminForm(FlaskForm):
    name = StringField(label='姓名')
    password = PasswordField(label='密码')
    role_id = SelectField(label='角色',coerce=int)
    comfirmed = BooleanField(label='邮箱认证')
    location = StringField(label='所在地')
    about_me = TextAreaField(label='AboutMe')
    submit = SubmitField(label='提交')

    def __init__(self,*args,**kwargs):
        super(EditAdminForm, self).__init__(*args,**kwargs)
        self.role_id.choices = [(role.id,role.name) for role in (Role.query.order_by(Role.id).all())]


class AddDevice(FlaskForm):
    name = StringField(label='设备名称',validators=[DataRequired()])
    about = TextAreaField(label='设备描述',validators=[DataRequired()])
    location = StringField(label='设备位置',validators=[DataRequired()])
    submit = SubmitField(label='添加设备')



class AddSensor(FlaskForm):
    name = StringField(label='传感器名称',validators=[DataRequired()])
    type = SelectField(label='传感器类型',coerce=int)
    about = TextAreaField(label='传感器描述',validators=[DataRequired()])
    unit = StringField(label='传感器单位',validators=[DataRequired()])
    max = FloatField(label='最大值')
    min = FloatField(label='最小值')
    submit = SubmitField(label='添加传感器')
    def __init__(self):
        super(AddSensor,self).__init__()
        self.type.choices = [(stype.id,stype.name) for stype in Stype.query.all()]


iot/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import forms, views

iot/app/main/views.py
from app.auth.forms import LoginForm
from flask_login import login_user, logout_user, current_user
from flask import render_template, session, abort, redirect, url_for, request, flash
from . import main
from app.models import User, db, Device, Sensor,Data,Waring
from .forms import EditUserinfo, EditAdminForm, AddDevice, AddSensor
from flask_login import login_required, current_user
from app.decorators import admin_decorator, permission_decorator
from app.decorators import Permission


@main.route('/', methods=['GET', 'POST'])
def index():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if (user is not None and user.check_password(form.password.data)):
            login_user(user, False)
            session['name'] = user.name
            return redirect(url_for('main.index'))
        else:
            flash('name or password is worry')
    return render_template('main/index.html', form=form)


@main.route('/user/<path:name>')
@login_required
def user_info(name):
    user = User.query.filter_by(name=name).first()
    if user is None:
        abort(404)
    return render_template('main/user_info.html', user=user)


@main.route('/edit_user_info', methods=['GET', 'POST'])
@login_required
def edit_user_info():
    form = EditUserinfo()
    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.user_info', name=current_user.name))
    return render_template('main/edit_user.html', form=form)


@main.route('/edit_admin', methods=['GET', 'POST'])
@login_required
@admin_decorator
def edit_admin():
    id = request.args.get('id', None)
    if id is None:
        abort(404)
    user = User.query.filter_by(id=id).first()
    form = EditAdminForm()
    if form.validate_on_submit():
        u1 = User.query.filter_by(name=form.name.data).first()
        if u1 is None:
            abort(404)
        if u1 and u1 != user:
            return redirect(url_for('main.user_info', name=user.name))
        user.name = form.name.data
        if form.password.data:
            user.password = form.password.data
        user.about_me = form.about_me.data
        user.location = form.location.data
        user.role_id = form.role_id.data
        user.confirmed = form.comfirmed.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.user_info', name=user.name))
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    form.comfirmed.data = user.confirmed
    form.role_id.data = user.role_id
    return render_template('main/edit_admin.html', form=form)


@main.route('/devices')
@login_required
def devices():
    page = request.args.get('page', 1, type=int)
    pagination = current_user.devices.order_by(Device.time.desc()).paginate(page, 3, False)
    ds = pagination.items
    return render_template('main/devices.html', ds=ds, pagination=pagination)


@main.route('/add_device', methods=['GET', 'POST'])
@login_required
def add_device():
    form = AddDevice()
    if form.validate_on_submit():
        device = Device()
        device.name = form.name.data
        device.about = form.about.data
        device.location = form.location.data
        device.user_id = current_user.id
        db.session.add(device)
        db.session.commit()
        return redirect(url_for('main.devices'))
    return render_template('main/add_device.html', form=form)


@main.route('/device_info')
@login_required
def device_info():
    did = request.args.get('did')
    page = request.args.get('page',1,type=int)
    if did is None:
        abort(404)
    d = current_user.devices.filter_by(id=did).first()
    pagination = d.sensors.order_by(Sensor.time.desc()).paginate(page,2,False)
    sensors = pagination.items
    return render_template('main/device_info.html', d=d, sensors=sensors,pagination=pagination)


@main.route('/add_sensor', methods=['GET', 'POST'])
@login_required
def add_sensor():
    form = AddSensor()
    did = request.args.get('did')
    if did is None:
        abort(404)
    device = current_user.devices.filter_by(id=did).first()
    if device is None:
        abort(404)
    if form.validate_on_submit():
        sensor = Sensor()
        sensor.type = form.type.data
        sensor.name = form.name.data
        sensor.about = form.about.data
        sensor.unit = form.unit.data
        sensor.max = form.max.data
        sensor.min = form.min.data
        sensor.device_id = did
        db.session.add(sensor)
        db.session.commit()
        return redirect(url_for('main.device_info', did=did))
    return render_template('main/add_sensor.html', form=form)


@main.route('/delete_device')
@login_required
def delete_device():
    did = request.args.get('did')
    if did is None:
        abort(404)
    device = current_user.devices.filter_by(id=did).first()
    if device is None:
        abort(404)
    db.session.delete(device)
    db.session.commit()
    return redirect(url_for('main.devices'))


@main.route('/edit_device', methods=['GET', 'POST'])
@login_required
def edit_device():
    did = request.args.get('did')
    if did is None:
        abort(404)
    device = current_user.devices.filter_by(id=did).first()
    if device is None:
        abort(404)
    form = AddDevice()
    if form.validate_on_submit():
        device.name = form.name.data
        device.about = form.about.data
        device.location = form.location.data
        db.session.add(device)
        db.session.commit()
        return redirect(url_for('main.devices'))
    form.name.data = device.name
    form.about.data = device.about
    form.location.data = device.location
    return render_template('main/edit_device.html', form=form)


@main.route('/delete_sensor')
@login_required
def delete_sensor():
    sid = request.args.get('sid')
    did = request.args.get('did')
    if sid is None or did is None:
        abort(404)
    device = current_user.devices.filter_by(id=did).first()
    if device is None:
        abort(404)
    sensor = device.sensors.filter_by(id=sid).first()
    if sensor is None:
        abort(404)
    db.session.delete(sensor)
    db.session.commit()
    return redirect(url_for('main.device_info', did=did))


@main.route('/edit_sensor', methods=['GET', 'POST'])
@login_required
def edit_sensor():
    sid = request.args.get('sid')
    did = request.args.get('did')
    if sid is None or did is None:
        abort(404)
    device = current_user.devices.filter_by(id=did).first()
    if device is None:
        abort(404)
    sensor = device.sensors.filter_by(id=sid).first()
    if sensor is None:
        abort(404)
    form = AddSensor()
    if form.validate_on_submit():
        sensor.type = form.type.data
        sensor.name = form.name.data
        sensor.about = form.about.data
        sensor.unit = form.unit.data
        sensor.max = form.max.data
        sensor.min = form.min.data
        db.session.add(sensor)
        db.session.commit()
        return redirect(url_for('main.device_info', did=did))
    form.name.data = sensor.name
    form.unit.data = sensor.unit
    form.about.data = sensor.about
    form.type.data = sensor.type
    form.max.data = sensor.max
    form.min.data = sensor.min
    return render_template('main/edit_sensor.html', form=form)

@main.route('/sensor_datas')
@login_required
def sensor_datas():
    page = request.args.get('page',1,type=int)
    did = request.args.get('did')
    sid = request.args.get('sid')
    if sid is None or did is None:
        abort(404)
    else:
        d = current_user.devices.filter_by(id=did).first()
        sensor = d.sensors.filter_by(id=sid).first()
        if sensor is None or d is None:
            abort(404)
        else:
            pagination = sensor.datas.paginate(page,30,False)
            datas = pagination.items
            return render_template('main/datas.html',pagination=pagination,datas=datas,sid=sid,did=did)


@main.route('/waring')
@login_required
def waring():
    page =request.args.get('page',1,type=int)
    pagination = current_user.warings.paginate(page,30,False)
    warings = pagination.items
    return render_template('main/waring.html',pagination=pagination,warings=warings)

iot/app/templates/main/add_device.html
{% extends 'base.html' %}
{% block bodystyle %}
<body class="index">
{% endblock %}
{% block page_content1 %}
{% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}
</body>

iot/app/templates/main/add_sensor.html
{% extends 'base.html'%}
{% block bodystyle %}
<body class="index">
{% endblock %}
{% block page_content1 %}
{% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}
</body>

iot/app/templates/main/datas.html
{% extends  'base.html' %}
{% block page_content1 %}
    <div class="panel panel-info">
        <!-- Default panel contents -->
        <div class="panel-heading" align="center">传感器数据</div>
        <!-- Table -->
        <table class="table" border="1">
            <tr>
                <th>编号</th>
                <th>数据</th>
                <th>时间</th>
            </tr>
            {% for data in datas %}
                <tr>
                    <td>{{ data.id }}</td>
                    <td>{{ data.data }}{{ data.sensor.unit }}</td>
                    <td>{{ data.time }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    {% import '_macro.html'as macro %}
    {{ macro.pagination_widget(pagination,'main.sensor_datas',sid= sid,did=did) }}
{% endblock %}

iot/app/templates/main/device_info.html
{% extends 'base.html' %}
{% block bodystyle %}
    <body class="wdsb">
{% endblock %}
{% block page_content %}
    <div class="main-container container clearfix">
        <div class="content" id="content">
            <div class="my-shebei">
                <h2>
                    设备详情
                    <a href="{{ url_for('main.add_sensor',did = d.id) }}">添加传感器</a>
                </h2>
                <div class="field-my">
                    <div class="row">
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                <a href="{{ url_for('main.device_info',did=d.id) }}"><img
                                        src="/static/images/shebei.jpg" alt="..."></a>
                            </div>
                        </div>
                        <div class="left">
                            <a href="{{ url_for('main.device_info',did=d.id) }}">
                                <div class="field-shebeiming">我是设备名称【id：{{ d.id }}】</div>
                            </a>
                            <div class="field-shebeiming">描述&nbsp;:&nbsp;{{ d.about }}</div>
                            <div class="field-shebeiming">名称：{{ d.name }}</div>
                            <div class="field-shebeiming">位置：{{ d.location }}</div>
                            <div class="field-shebeiming">时间：{{ moment(d.time).format('LLLL') }}</div>
                            <a href="#" class="btn btn-info">共{{ d.sensors.count() }}个传感器</a>
                        </div>
                    </div>
                </div>
            </div>

            {#          {% import '_macro.html'as macro %}#}
            {#        {{ macro.pagination_widget(pagination,'main.devices') }}#}

        </div>
        <div class="sidebar-second" id="sidebar">
            <div class="block-sidebar block-sidebar-2">
                <p><img src="/static/images/banner.png"/></p>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_content2 %}
    <h2>传感器</h2>
    {% for sensor in sensors %}
        <div class="left my-shebei field-my">
            <div class="field-shebeiming"> 传感器id&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                : {{ sensor.id }}</div>
            <div class="field-shebeiming"> 传感器名称&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;：{{ sensor.name }}</div>
            <div class="field-shebeiming"> 传感器类型&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;：{{ sensor.s_type.name }}</div>
            <div class="field-shebeiming"> 传感器描述 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ：{{ sensor.about }}</div>
            <div class="field-shebeiming"> 传感器单位 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ：{{ sensor.unit }}</div>
            <div class="field-shebeiming"> 传感器创建时间 ：{{ sensor.time }}</div>
            <a href="{{ url_for('main.delete_sensor',sid=sensor.id,did = d.id) }}"
               class="btn glyphicon glyphicon-trash btn-warning"></a>
            <a href="{{ url_for('main.edit_sensor',sid=sensor.id,did = d.id) }}"
               class="btn glyphicon glyphicon-cog btn-info"></a>
            <a href="{{ url_for('main.sensor_datas',sid = sensor.id,did= d.id) }}" class="btn bg-success">共{{ sensor.datas.count() }}数据</a>
        </div>
    {% endfor %}
    {% import '_macro.html'as macro %}
    {{ macro.pagination_widget(pagination,'main.device_info',did=d.id) }}
{% endblock %}
</body>

iot/app/templates/main/devices.html
{% extends 'base.html' %}
{% block bodystyle %}
    <body class="wdsb">
{% endblock %}
{% block page_content %}

    <div class="main-container container clearfix">
        <div class="content" id="content">
            <div class="my-shebei">
                <h2>
                    我的全部设备
                    <a href="{{ url_for('main.add_device',uid = current_user.id) }}">添加设备</a>
                </h2>
                <div class="field-my">
                    {% for d in ds %}
                        <div class="row">
                            <div class="col-sm-6 col-md-4">
                                <div class="thumbnail">
                                    <a href="{{ url_for('main.device_info',did=d.id) }}"><img
                                            src="/static/images/shebei.jpg" alt="..."></a>
                                </div>
                            </div>
                            <div class="left">
                                <a href="{{ url_for('main.device_info',did=d.id) }}">
                                    <div class="field-shebeiming">我是设备名称【id：{{ d.id }}】</div>
                                </a>
                                <div class="field-shebeiming">描述&nbsp;:  {{ d.about }}</div>
                                <div class="field-shebeiming">名称：{{ d.name }}</div>
                                <div class="field-shebeiming">位置：{{ d.location }}</div>
                                <div class="field-shebeiming">时间：{{ moment(d.time).format('LLLL') }}</div>
                               <a href="{{ url_for('main.delete_device',did=d.id) }}" class="btn glyphicon glyphicon-trash btn-warning"></a>
                                <a href="{{ url_for('main.edit_device',did=d.id) }}" class="btn glyphicon glyphicon-cog btn-info" ></a>
                                <a href="{{ url_for('main.device_info',did=d.id) }}" class="btn bg-success">传感器</a>
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </div>

          {% import '_macro.html'as macro %}
        {{ macro.pagination_widget(pagination,'main.devices') }}

        </div>
        <div class="sidebar-second" id="sidebar">
            <div class="block-sidebar block-sidebar-2">
                <p><img src="/static/images/banner.png"/></p>
            </div>
        </div>
    </div>
{% endblock %}

</body>

iot/app/templates/main/edit_admin.html
{% extends 'base.html' %}
{% block bodystyle %}
<body class="index">
{% endblock %}
{% block page_content %}
    {% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}
</body>

iot/app/templates/main/edit_device.html
{% extends 'base.html' %}
{% block bodystyle %}
<body class="index">
{% endblock %}
{% block page_content1 %}
{% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}
</body>

iot/app/templates/main/edit_sensor.html
{% extends 'base.html' %}
{% block bodystyle %}
    <body class="grzx">
{% endblock %}
{% block page_content1 %}
    {% import 'bootstrap/wtf.html'as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}
</body>

iot/app/templates/main/edit_user.html
{% extends 'base.html' %}
{% block page_content %}
    {% import 'bootstrap/wtf.html' as wtf %}
    {{ wtf.quick_form(form) }}
{% endblock %}

iot/app/templates/main/index.html
{% extends 'base.html' %}
{% block bodystyle %}
    <body class="index">
{% endblock %}
{% block page_content %}


<div class="highlighted">
    <div class="sliders">
        <ul>
            <li class="list-1"
                style="background: url('/static/images/sliders1.jpg') center top #000 no-repeat;height: 580px;">
                <div class="container">
                    <div class="slider-title slider-title-animation"><img src="/static/images/sliders1-1.png"/>
                    </div>
                    <p class="p-animation">
                        尚观独立研发，只能设备连接平台，设备智能化研发、接入、管理一体化<br/>
                        平台快速、高校、低成本实现产品智能化
                    </p>
                    <a href="###" class="btn btn-animation">了解物联网服务器</a>
                </div>
            </li>
            <li class="list-2"
                style="background: url('/static/images/sliders1.jpg') center top #000 no-repeat;height: 580px;">
                <div class="container">
                    <div class="slider-title"><img src="/static/images/sliders1-1.png"/></div>
                    <p>
                        尚观独立研发，只能设备连接平台，设备智能化研发、接入、管理一体化<br/>
                        平台快速、高校、低成本实现产品智能化
                    </p>
                    <a href="###" class="btn">了解物联网服务器</a>
                </div>
            </li>
        </ul>
    </div>
    {% if not current_user.is_authenticated %}
    <div class="slider-form">
        <div class="slider-form-box">
            <h2>登录</h2>
            <div class="webfrom">
                <form action="" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.email(type="text",class="form-control",id="zhanghao",placeholder="请输入账号") }}
                    </div>
                    {% for msg in get_flashed_messages() %}
                    <span class="btn-warning">{{ msg }}</span>
                    {% endfor %}
                    <div class="form-group">
                        {{ form.password(type="password",class="form-control",id="password",
                               placeholder="请输入密码") }}
                    </div>
                    <button type="submit" class="btn center-block">登录</button>
                </form>
            </div>
            <div class="caozuo clearfix">
                <div class="wangji"><a href="#">记住密码？</a></div>
                <div class="zhuce"><a href="{{ url_for('auth.register') }}">立即注册</a></div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<div class="main-container container clearfix">
    <div id="ditu" style="width: 1000px;height:715px;"></div>
</div>

<script src="/static/js/echarts.js"></script>
<script src="/static/js/china.js"></script>
<script src="/static/js/ditu.js"></script>

<script>
    $(document).ready(function () {
        $('.sliders').unslider({
            speed: 500,
            delay: 5000,
            starting: function () {
                $(".highlighted .slider-title").removeClass('slider-title-animation');
                $(".highlighted p").removeClass('p-animation');
                $(".highlighted li .btn").removeClass('btn-animation');
            },
            complete: function () {

                $(".highlighted .slider-title").addClass('slider-title-animation');
                $(".highlighted p").addClass('p-animation');
                $(".highlighted li .btn").addClass('btn-animation');
            },
            dots: true
        });
    });
</script>
{% endblock %}
</body>

iot/app/templates/main/user_info.html
{% extends 'base.html' %}

{% block bodystyle %}
    <body class="grzx">
{% endblock %}
{% block page_content %}



    <div class="main-container container clearfix">
        <div class="content" id="content">
            <div class="add-btn">
                <a type="button" class="btn" href="{{ url_for('main.devices') }}">我的设备</a>
            </div>
            <div class="shebei">
                <ul>
                    <li>
                        <div class="field-title clearfix">
                            <a href="#">我是标题</a>
                            <span>我是作者&nbsp;&nbsp;&nbsp;&nbsp;3分钟前</span>
                        </div>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet.
                            Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvin
                            ar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculu
                        </p>
                    </li>
                </ul>
            </div>

            <div class="page-pager">
                <ul class="pagination">
                    <li><a href="#">上一页</a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">下一页</a></li>
                </ul>
            </div>

        </div>
        <div class="sidebar-second" id="sidebar">
            <div class="block-sidebar block-sidebar-1">
                <div class="group-btn">
                    {% if current_user==user and not current_user.is_admin %}
                        <a type="button" class="btn btn-edit" href="{{ url_for('main.edit_user_info') }}">编辑资料</a>
                    {% endif %}
                    {% if current_user.is_admin %}
                        <a type="button" class="btn btn-edit" href="{{ url_for('main.edit_admin',id=user.id) }}">编辑资料</a>
                    {% endif %}
                </div>
                <div class="block-sidebar-views">
                    <p><span>API-KEY：</span>{{ user.api_key }}</p>
                    <p><span>个人介绍：</span>{{ user.about_me }}</p>
                    <p><span>位置：</span>{{ user.location }}</p>
                    <p><span>用户类型：</span>{{ user.role.name }}</p>
                    <p><span>邮箱：</span>{{ user.email }}</p>
                    <p><span>验证：</span>邮箱验证通过</p>
                    <p><span>注册时间：</span>{{ user.register_time }}</p>
                    <p><span>最后访问时间：</span>{{ moment(user.access_time).fromNow() }}</p>
                </div>
                <div class="block-sidebar-footer">
                    我的关注：20&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    我的粉丝：66
                </div>
            </div>
        </div>
    </div>


    </body>
{% endblock %}

iot/app/templates/main/waring.html
{% extends 'base.html' %}
{% block page_content1 %}
    <div class="panel panel-info">
        <!-- Default panel contents -->
        <div class="panel-heading" align="center">报警数据共{{ current_user.warings.count() }}条</div>
        <!-- Table -->
        <table class="table" border="1">
            <tr>
                <th>设备ID</th>
                <th>设备名</th>
                <th>传感器ID</th>
                <th>传感器名称</th>
                <th>报警值</th>
                <th>上限</th>
                <th>下限</th>
                <th>报警信息</th>
                <th>报警时间</th>
            </tr>
            {% for w in warings %}
                <tr>
                    <td>{{ w.device.id }}</td>
                    <td>{{ w.device.name }}</td>
                    <td>{{ w.sensor.id }}</td>
                    <td>{{ w.sensor.name }}</td>
                    <td>{{ w.data }}{{ w.sensor.unit }}</td>
                    <td>{{ w.max }}</td>
                    <td>{{ w.min }}</td>
                    <td>{{ w.about }}</td>
                    <td>{{ w.time }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    {% import '_macro.html'as macro %}
    {{ macro.pagination_widget(pagination,'main.waring') }}
{% endblock %}